#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// resend-client — One-time secret setup script
// Run: node scripts/setup-secrets.mjs
//
// What it does:
//   1. Generates MASTER_ENCRYPTION_KEY + JWT_SECRET (cryptographically random)
//   2. Prompts for admin username + password → SHA-256 hashes the password
//   3. Writes all values to .dev.vars (local dev)
//   4. Prints the `wrangler secret bulk` JSON for production deploy
// ─────────────────────────────────────────────────────────────────────────────

import { randomBytes, createHash } from 'node:crypto'
import { createInterface } from 'node:readline'
import { writeFileSync, existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const rl = createInterface({ input: process.stdin, output: process.stdout })
const ask = (q) => new Promise((resolve) => rl.question(q, resolve))

const ROOT = resolve(import.meta.dirname, '..')
const DEV_VARS_PATH = resolve(ROOT, '.dev.vars')

console.log('\n🚀  resend-client — Secret Setup\n')
console.log('This script generates all required secrets for local dev and production.\n')

// ── 1. Generate random secrets ──────────────────────────────────────────────

const masterKey = randomBytes(32).toString('hex')
const jwtSecret  = randomBytes(48).toString('hex')

// ── 2. Prompt for admin credentials ─────────────────────────────────────────

const username = (await ask('Admin username [default: admin]: ')).trim() || 'admin'

let password = ''
while (!password) {
  password = (await ask('Admin password (min 8 chars): ')).trim()
  if (password.length < 8) {
    console.log('  ⚠️  Password must be at least 8 characters. Try again.\n')
    password = ''
  }
}

const passwordHash = createHash('sha256').update(password).digest('hex')

rl.close()

// ── 3. Write .dev.vars ───────────────────────────────────────────────────────

const devVarsContent = `# resend-client local dev secrets — DO NOT commit this file
# Generated by: node scripts/setup-secrets.mjs

MASTER_ENCRYPTION_KEY=${masterKey}
JWT_SECRET=${jwtSecret}
ADMIN_USERNAME=${username}
ADMIN_PASSWORD_HASH=${passwordHash}
ENVIRONMENT=development
`

// Backup existing .dev.vars if present
if (existsSync(DEV_VARS_PATH)) {
  const backup = DEV_VARS_PATH + '.backup'
  writeFileSync(backup, readFileSync(DEV_VARS_PATH))
  console.log(`\n📦  Backed up existing .dev.vars → .dev.vars.backup`)
}

writeFileSync(DEV_VARS_PATH, devVarsContent)
console.log(`✅  Written to: .dev.vars\n`)

// ── 4. Print production deploy JSON ─────────────────────────────────────────

const bulkJson = JSON.stringify({
  MASTER_ENCRYPTION_KEY: masterKey,
  JWT_SECRET: jwtSecret,
  ADMIN_USERNAME: username,
  ADMIN_PASSWORD_HASH: passwordHash,
}, null, 2)

console.log('─'.repeat(60))
console.log('📋  Production secrets (for GitHub Actions / wrangler secret bulk):')
console.log('─'.repeat(60))
console.log(bulkJson)
console.log('─'.repeat(60))

// ── 5. Next steps ────────────────────────────────────────────────────────────

console.log(`
📌  Next Steps:

  LOCAL DEV — already done! Just run:
    pnpm dev

  PRODUCTION — add these secrets to GitHub repo:
    Settings → Secrets & variables → Actions → New repository secret

    CLOUDFLARE_API_TOKEN    → get from: https://dash.cloudflare.com/profile/api-tokens
    CLOUDFLARE_ACCOUNT_ID   → get from: https://dash.cloudflare.com (right sidebar)
    MASTER_ENCRYPTION_KEY   → ${masterKey.slice(0, 8)}... (see JSON above)
    JWT_SECRET              → ${jwtSecret.slice(0, 8)}... (see JSON above)
    ADMIN_USERNAME          → ${username}
    ADMIN_PASSWORD_HASH     → ${passwordHash.slice(0, 8)}... (see JSON above)

  Or deploy secrets directly with:
    echo '${bulkJson.replace(/\n/g, ' ')}' | npx wrangler secret bulk --config wrangler.jsonc

  Then push to main to trigger auto-deploy → GitHub Actions → Cloudflare 🚀
`)
